services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://api.emplacc.g-309.ru}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - emplacc-network
